//
//  ReferalConfigurator.swift
//  contrast
//
//  Created by Vladimir Kotovchikhin on 29.06.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

final class ReferalConfigurator {
    
    static let shared = ReferalConfigurator()
    private init() {}
    
    func configure(_ viewController: ReferalViewController) {
        let service = NetworkService()
        let interactor = ReferalInteractor(service: service)
        let presenter = ReferalPresenter()
        let router = ReferalRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
}
