//
//  ReferalPresenter.swift
//  contrast
//
//  Created by Vladimir Kotovchikhin on 29.06.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ReferalPresentationLogic {
    func presentData(response: Referal.Model.Response.ResponseType)
}

final class ReferalPresenter {
    
    // MARK: - External vars
    weak var viewController: ReferalDisplayLogic?
    
}

// MARK: - Presentation logic
extension ReferalPresenter: ReferalPresentationLogic {
    
    func presentData(response: Referal.Model.Response.ResponseType) {
        switch response {
        case .referalCodeStatus(let status):
            viewController?.display(viewModel: .referalCodeStatus(status))
        }
    }
}

//  MARK: - Private  methods
private extension ReferalPresenter {
    
}
