//
//  ReferalRouter.swift
//  contrast
//
//  Created by Vladimir Kotovchikhin on 29.06.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ReferalRoutingLogic {
    func routeToLogInParams()
}

protocol ReferalDataPassing {
    var dataStore: ReferalDataStore? { get }
}

final class ReferalRouter: NSObject {
    
    // MARK: - External vars
    weak var viewController: ReferalViewController?
    var dataStore: ReferalDataStore?
    
    // MARK: - Internal vars
    
}

// MARK: - Routing logic
extension ReferalRouter: ReferalRoutingLogic {
    func routeToLogInParams() {
        if UserDefaultsWorker.fetchOfferEnterCode() == false {
            let vc = LogInParamsViewController()
            viewController?.navigationController?.pushViewController(vc, animated: true)
        } else {
            let vc = ProfileViewController()
            viewController?.navigationController?.pushViewController(vc, animated: true)
        }
    }
}

// MARK: - Data passing
extension ReferalRouter: ReferalDataPassing {
    
}
