//
//  SmsConfirmRouter.swift
//  contrast
//
//  Created by Александра Орлова on 03.07.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SmsConfirmRoutingLogic {
    func routeToLoginParams()
    func routeToReferal()
}

protocol SmsConfirmDataPassing {
    var dataStore: SmsConfirmDataStore? { get }
}

final class SmsConfirmRouter: NSObject {
    
    // MARK: - External vars
    weak var viewController: SmsConfirmViewController?
    var dataStore: SmsConfirmDataStore?
    
    // MARK: - Internal vars
    
}

// MARK: - Routing logic
extension SmsConfirmRouter: SmsConfirmRoutingLogic {
    func routeToLoginParams() {
        
        if UserDefaultsWorker.fetchOfferEnterCode() == false {
            let vc = LogInParamsViewController()
            viewController?.navigationController?.pushViewController(vc, animated: true)
        } else {
            let vc = ProfileViewController()
            viewController?.navigationController?.pushViewController(vc, animated: true)
        }
    }
    
    func routeToReferal() {
        let vc = ReferalViewController()
        viewController?.navigationController?.pushViewController(vc, animated: true)
    }
}

// MARK: - Data passing
extension SmsConfirmRouter: SmsConfirmDataPassing {
    
}
