//
//  LogInParamsPresenter.swift
//  contrast
//
//  Created by Александра Орлова on 29.06.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LogInParamsPresentationLogic {
    func presentData(response: LogInParams.Model.Response.ResponseType)
}

final class LogInParamsPresenter {
    
    // MARK: - External vars
    weak var viewController: LogInParamsDisplayLogic?
    
}

// MARK: - Presentation logic
extension LogInParamsPresenter: LogInParamsPresentationLogic {
    
    func presentData(response: LogInParams.Model.Response.ResponseType) {
        switch response {
            //case .some:
        }
    }
}

//  MARK: - Private  methods
private extension LogInParamsPresenter {
    
}
