//
//  LogInParamsRouter.swift
//  contrast
//
//  Created by Александра Орлова on 29.06.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LogInParamsRoutingLogic {
    func routeToPincode()
    func routeToMain()
}

protocol LogInParamsDataPassing {
    var dataStore: LogInParamsDataStore? { get }
}

final class LogInParamsRouter: NSObject {
    
    // MARK: - External vars
    weak var viewController: LogInParamsViewController?
    var dataStore: LogInParamsDataStore?
    
    // MARK: - Internal vars
    
}

// MARK: - Routing logic
extension LogInParamsRouter: LogInParamsRoutingLogic {
    func routeToPincode() {
        let vc = PincodeSetViewController()
        viewController?.navigationController?.pushViewController(vc, animated: true)
    }
    
    func routeToMain() {
        let vc = TabbarViewController()
        viewController?.navigationController?.pushViewController(vc, animated: true)
    }
}

// MARK: - Data passing
extension LogInParamsRouter: LogInParamsDataPassing {
    
}
