//
//  LogInParamsInteractor.swift
//  contrast
//
//  Created by Александра Орлова on 29.06.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LogInParamsBusinessLogic {
    func make(request: LogInParams.Model.Request.RequestType)
}

protocol LogInParamsDataStore: AnyObject {
    
}

final class LogInParamsInteractor {
    
    // MARK: - External vars
    var presenter: LogInParamsPresentationLogic?
    var worker: LogInParamsWorker?
    
    // MARK: - Internal vars
    private let service: Services
    
    init(service: NetworkServiceable) {
        self.service = Services(service: service)
    }
}

// MARK: - Business logic
extension LogInParamsInteractor: LogInParamsBusinessLogic {
    
    func make(request: LogInParams.Model.Request.RequestType) {
        switch request {
            //case .some:
        }
    }
}

// MARK: - Data store
extension LogInParamsInteractor: LogInParamsDataStore  {
   
}

// MARK: - Private methods
private extension LogInParamsInteractor {
    
}
