//
//  StoriesConfigurator.swift
//  contrast
//
//  Created by Александра Орлова on 10.07.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

final class StoriesConfigurator {
    
    static let shared = StoriesConfigurator()
    private init() {}
    
    func configure(_ viewController: StoriesViewController) {
        let service = NetworkService()
        let interactor = StoriesInteractor(service: service)
        let presenter = StoriesPresenter()
        let router = StoriesRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
}
