//
//  PincodeSetRouter.swift
//  contrast
//
//  Created by Александра Орлова on 29.06.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PincodeSetRoutingLogic {
    func routeToMain()
}

protocol PincodeSetDataPassing {
    var dataStore: PincodeSetDataStore? { get }
}

final class PincodeSetRouter: NSObject {
    
    // MARK: - External vars
    weak var viewController: PincodeSetViewController?
    var dataStore: PincodeSetDataStore?
    
    // MARK: - Internal vars
    
}

// MARK: - Routing logic
extension PincodeSetRouter: PincodeSetRoutingLogic {
    func routeToMain() {
        let vc = TabbarViewController()
        viewController?.navigationController?.pushViewController(vc, animated: true)
    }
}

// MARK: - Data passing
extension PincodeSetRouter: PincodeSetDataPassing {
    
}
