//
//  PincodeSetConfigurator.swift
//  contrast
//
//  Created by Александра Орлова on 29.06.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

final class PincodeSetConfigurator {
    
    static let shared = PincodeSetConfigurator()
    private init() {}
    
    func configure(_ viewController: PincodeSetViewController) {
        let service = NetworkService()
        let interactor = PincodeSetInteractor(service: service)
        let presenter = PincodeSetPresenter()
        let router = PincodeSetRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
}
