//
//  PincodeSetInteractor.swift
//  contrast
//
//  Created by Александра Орлова on 29.06.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PincodeSetBusinessLogic {
    func make(request: PincodeSet.Model.Request.RequestType)
}

protocol PincodeSetDataStore: AnyObject {
    
}

final class PincodeSetInteractor {
    
    // MARK: - External vars
    var presenter: PincodeSetPresentationLogic?
    var worker: PincodeSetWorker?
    
    // MARK: - Internal vars
    private let service: Services
    
    init(service: NetworkServiceable) {
        self.service = Services(service: service)
    }
}

// MARK: - Business logic
extension PincodeSetInteractor: PincodeSetBusinessLogic {
    
    func make(request: PincodeSet.Model.Request.RequestType) {
        switch request {
            //case .some:
        }
    }
}

// MARK: - Data store
extension PincodeSetInteractor: PincodeSetDataStore  {
   
}

// MARK: - Private methods
private extension PincodeSetInteractor {
    
}
