//
//  AddressClarificationRouter.swift
//  contrast
//
//  Created by Roman Kiruxin on 18.07.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AddressClarificationRoutingLogic {
    func routeToTimeIntervalOrdering(activeZones: [ZonesGeolocateInfo],
                                     addressData: UserAddressRequest,
                                     isSaveAddress: Bool)
}

protocol AddressClarificationDataPassing {
    var dataStore: AddressClarificationDataStore? { get }
}

final class AddressClarificationRouter: NSObject {
    
    // MARK: - External vars
    weak var viewController: AddressClarificationViewController?
    var dataStore: AddressClarificationDataStore?
    
    // MARK: - Internal vars
    
}

// MARK: - Routing logic
extension AddressClarificationRouter: AddressClarificationRoutingLogic {
    func routeToTimeIntervalOrdering(activeZones: [ZonesGeolocateInfo], addressData: UserAddressRequest, isSaveAddress: Bool) {
        let vc = TimeIntervalsOrderingViewController()
        vc.router?.dataStore?.activeZones = activeZones
        vc.router?.dataStore?.addressData = addressData
        vc.router?.dataStore?.isSaveAddress = isSaveAddress
        let nc = UINavigationController(rootViewController: vc)
        nc.modalPresentationStyle = .fullScreen
        viewController?.present(nc, animated: true)
    }
}

// MARK: - Data passing
extension AddressClarificationRouter: AddressClarificationDataPassing {
    
}
