//
//  AddressClarificationPresenter.swift
//  contrast
//
//  Created by Roman Kiruxin on 18.07.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AddressClarificationPresentationLogic {
    func presentData(response: AddressClarification.Model.Response.ResponseType)
}

final class AddressClarificationPresenter {
    
    // MARK: - External vars
    weak var viewController: AddressClarificationDisplayLogic?
    
}

// MARK: - Presentation logic
extension AddressClarificationPresenter: AddressClarificationPresentationLogic {
    
    func presentData(response: AddressClarification.Model.Response.ResponseType) {
        switch response {
            
        }
    }
}

//  MARK: - Private  methods
private extension AddressClarificationPresenter {
    
}
