//
//  AddressClarificationConfigurator.swift
//  contrast
//
//  Created by Roman Kiruxin on 18.07.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

final class AddressClarificationConfigurator {
    
    static let shared = AddressClarificationConfigurator()
    private init() {}
    
    func configure(_ viewController: AddressClarificationViewController) {
        let service = NetworkService()
        let interactor = AddressClarificationInteractor(service: service)
        let presenter = AddressClarificationPresenter()
        let router = AddressClarificationRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
}
