//
//  TimeSlotsRouter.swift
//  contrast
//
//  Created by Roman Kiruxin on 05.07.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TimeSlotsRoutingLogic {
    func dismissScreen()
}

protocol TimeSlotsDataPassing {
    var dataStore: TimeSlotsDataStore? { get }
}

final class TimeSlotsRouter: NSObject {
    
    // MARK: - External vars
    weak var viewController: TimeSlotsViewController?
    var dataStore: TimeSlotsDataStore?
    
    // MARK: - Internal vars
    
}

// MARK: - Routing logic
extension TimeSlotsRouter: TimeSlotsRoutingLogic {
    func dismissScreen() {
        viewController?.dismiss(animated: true)
    }
}

// MARK: - Data passing
extension TimeSlotsRouter: TimeSlotsDataPassing {
    
}
