//
//  TimeSlotsConfigurator.swift
//  contrast
//
//  Created by Roman Kiruxin on 05.07.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

final class TimeSlotsConfigurator {
    
    static let shared = TimeSlotsConfigurator()
    private init() {}
    
    func configure(_ viewController: TimeSlotsViewController) {
        let service = NetworkService()
        let interactor = TimeSlotsInteractor(service: service)
        let presenter = TimeSlotsPresenter()
        let router = TimeSlotsRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
}
