//
//  TimeSlotsModels.swift
//  contrast
//
//  Created by Roman Kiruxin on 05.07.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum TimeSlots {
    
    enum Model {
        struct Request {
            enum RequestType {
                case fetchIntervals
            }
        }
        struct Response {
            enum ResponseType {
                case fetchedIntervals(_ response: [TimeIntervalResponse])
            }
        }
        struct ViewModel {
            enum ViewModelType {
                case intervals(_ intervals: [TimeIntervalModel])
            }
        }
    }
}

struct TimeIntervalModel {
    let day: String
    let month: String
    var intervals: [IntervalModel]
    var isActive: Bool
}

struct IntervalModel: Decodable {
    let id: Int
    let timeStarts: String
    let timeFinish: String
    var isActive: Bool
}

