//
//  OnBoardingRouter.swift
//  contrast
//
//  Created by Roman Kiruxin on 28.06.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol OnBoardingRoutingLogic {
    func routeToLogin()
    func routeToPincode()
}

protocol OnBoardingDataPassing {
    var dataStore: OnBoardingDataStore? { get }
}

final class OnBoardingRouter: NSObject {
    
    // MARK: - External vars
    weak var viewController: OnBoardingViewController?
    var dataStore: OnBoardingDataStore?
    
    // MARK: - Internal vars

}

// MARK: - Routing logic
extension OnBoardingRouter: OnBoardingRoutingLogic {

    func routeToLogin() {
        let vc = LoginViewController()
        viewController?.navigationController?.pushViewController(vc, animated: true)
    }
    
    func routeToPincode() {
        let vc = LogInParamsViewController()
        viewController?.navigationController?.pushViewController(vc, animated: true)
    }
}

// MARK: - Data passing
extension OnBoardingRouter: OnBoardingDataPassing {
    
}
