//
//  OnBoardingModels.swift
//  contrast
//
//  Created by Roman Kiruxin on 28.06.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum OnBoarding {
    
    enum Model {
        struct Request {
            enum RequestType {
                
            }
        }
        struct Response {
            enum ResponseType {
                
            }
        }
        struct ViewModel {
            enum ViewModelType {
                
            }
        }
    }
}
