//
//  ProfileRouter.swift
//  contrast
//
//  Created by Roman Kiruxin on 29.06.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProfileRoutingLogic {
    func routeToAuth()
}

protocol ProfileDataPassing {
    var dataStore: ProfileDataStore? { get }
}

final class ProfileRouter: NSObject {
    
    // MARK: - External vars
    weak var viewController: ProfileViewController?
    var dataStore: ProfileDataStore?
    
    // MARK: - Internal vars
    
}

// MARK: - Routing logic
extension ProfileRouter: ProfileRoutingLogic {
    func routeToAuth() {
        let vc = LoginViewController()
        viewController?.navigationController?.pushViewController(vc, animated: true)
    }
}

// MARK: - Data passing
extension ProfileRouter: ProfileDataPassing {
    
}
