# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'contrast' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  #Yandex
   pod 'YandexMobileMetrica', '4.5.2'
   pod 'YandexMapsMobile', '4.3.1-lite'
   #Utilits
    pod 'Kingfisher', '6.2.1'
    pod 'R.swift', '5.4.0'
    pod 'PanModal'#, '1.2.7'
    pod 'SnapKit'
    pod 'Moya'
    pod 'KeychainAccess'
    pod 'Wormholy', :configurations => ['Debug']
    pod 'SwiftMessages'
    pod 'BEMCheckBox'
   #Firebase
    pod 'Firebase/Analytics'
    pod 'Firebase/Messaging'

end

post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
               end
          end
   end
end
