//
//  LinkNewCardInteractor.swift
//  contrast
//
//  Created by Александра Орлова on 07.07.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LinkNewCardBusinessLogic {
    func make(request: LinkNewCard.Model.Request.RequestType)
}

protocol LinkNewCardDataStore: AnyObject {
    var order: NewOrderModel? { get set }
}

final class LinkNewCardInteractor {
    
    // MARK: - External vars
    var presenter: LinkNewCardPresentationLogic?
    var worker: LinkNewCardWorker?
    var order: NewOrderModel? 
    
    // MARK: - Internal vars
    private let service: Services
    
    init(service: NetworkServiceable) {
        self.service = Services(service: service)
    }
}

// MARK: - Business logic
extension LinkNewCardInteractor: LinkNewCardBusinessLogic {
    
    func make(request: LinkNewCard.Model.Request.RequestType) {
        switch request {
            //case .some:
        }
    }
}

// MARK: - Data store
extension LinkNewCardInteractor: LinkNewCardDataStore  {
   
}

// MARK: - Private methods
private extension LinkNewCardInteractor {
    
}
