//
//  LinkNewCardConfigurator.swift
//  contrast
//
//  Created by Александра Орлова on 07.07.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

final class LinkNewCardConfigurator {
    
    static let shared = LinkNewCardConfigurator()
    private init() {}
    
    func configure(_ viewController: LinkNewCardViewController) {
        let service = NetworkService()
        let interactor = LinkNewCardInteractor(service: service)
        let presenter = LinkNewCardPresenter()
        let router = LinkNewCardRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
}
