//
//  LinkNewCardPresenter.swift
//  contrast
//
//  Created by Александра Орлова on 07.07.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LinkNewCardPresentationLogic {
    func presentData(response: LinkNewCard.Model.Response.ResponseType)
}

final class LinkNewCardPresenter {
    
    // MARK: - External vars
    weak var viewController: LinkNewCardDisplayLogic?
    
}

// MARK: - Presentation logic
extension LinkNewCardPresenter: LinkNewCardPresentationLogic {
    
    func presentData(response: LinkNewCard.Model.Response.ResponseType) {
        switch response {
            //case .some:
        }
    }
}

//  MARK: - Private  methods
private extension LinkNewCardPresenter {
    
}
