//
//  ContactsConfigurator.swift
//  contrast
//
//  Created by Roman Kiruxin on 29.06.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

final class ContactsConfigurator {
    
    static let shared = ContactsConfigurator()
    private init() {}
    
    func configure(_ viewController: ContactsViewController) {
        let service = NetworkService()
        let interactor = ContactsInteractor(service: service)
        let presenter = ContactsPresenter()
        let router = ContactsRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
}
