//
//  QrCodeConfigurator.swift
//  contrast
//
//  Created by Kotovchikhin Vladimir on 06.07.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

final class QrCodeConfigurator {
    
    static let shared = QrCodeConfigurator()
    private init() {}
    
    func configure(_ viewController: QrCodeViewController) {
        let service = NetworkService()
        let interactor = QrCodeInteractor(service: service)
        let presenter = QrCodePresenter()
        let router = QrCodeRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
}
