//
//  QrCodeInteractor.swift
//  contrast
//
//  Created by Kotovchikhin Vladimir on 06.07.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol QrCodeBusinessLogic {
    func make(request: QrCode.Model.Request.RequestType)
}

protocol QrCodeDataStore: AnyObject {
    var image: UIImage? { get set }
}

final class QrCodeInteractor {
    
    // MARK: - External vars
    var presenter: QrCodePresentationLogic?
    var worker: QrCodeWorker?
    var image: UIImage?
    
    
    // MARK: - Internal vars
    private let service: Services
    
    init(service: NetworkServiceable) {
        self.service = Services(service: service)
    }
}

// MARK: - Business logic
extension QrCodeInteractor: QrCodeBusinessLogic {
    
    func make(request: QrCode.Model.Request.RequestType) {
        switch request {
            //case .some:
        }
    }
}

// MARK: - Data store
extension QrCodeInteractor: QrCodeDataStore  {
   
}

// MARK: - Private methods
private extension QrCodeInteractor {
    
}
