//
//  QrCodeRouter.swift
//  contrast
//
//  Created by Kotovchikhin Vladimir on 06.07.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol QrCodeRoutingLogic {
    
}

protocol QrCodeDataPassing {
    var dataStore: QrCodeDataStore? { get }
}

final class QrCodeRouter: NSObject {
    
    // MARK: - External vars
    weak var viewController: QrCodeViewController?
    var dataStore: QrCodeDataStore?
    
    // MARK: - Internal vars
    
}

// MARK: - Routing logic
extension QrCodeRouter: QrCodeRoutingLogic {
    
}

// MARK: - Data passing
extension QrCodeRouter: QrCodeDataPassing {
    
}
