//
//  OrderingConfigurator.swift
//  contrast
//
//  Created by Kotovchikhin Vladimir on 14.07.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

final class OrderingConfigurator {
    
    static let shared = OrderingConfigurator()
    private init() {}
    
    func configure(_ viewController: OrderingViewController) {
        let service = NetworkService()
        let interactor = OrderingInteractor(service: service)
        let presenter = OrderingPresenter()
        let router = OrderingRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
}
