//
//  MainDashboardModels.swift
//  contrast
//
//  Created by Roman Kiruxin on 29.06.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum MainDashboard {
    
    enum Model {
        struct Request {
            enum RequestType {
                case fetchStories
            }
        }
        struct Response {
            enum ResponseType {
                case stories(_ response: [StoriesResponse])
            }
        }
        struct ViewModel {
            enum ViewModelType {
                case presentStories(_ viewModel: [StoriesModel])
            }
        }
    }
}

enum ScreensFromMain {
    case notifications
    case timeSlots
    case pdfView(nameScreen: String, url: String)
    case trustArrangement
    case qrCode(image: UIImage)
    case paymentMethod
    case estimate
    case stories(model: StoriesModel)
}

enum OrderStatus: Int {
    case created = 0, onWay, agreement, approved, rejected, refund, inProgress, ready, keeping, done
}

enum PaymentType {
    case card, cash
}

struct StoriesModel {
    let id: Int
    let title: String
    let description: String
    let promocode: String?
    let mediaType: Int
    let mediaLink: String
    let previewLink: String
}

struct OrderModel {
    let id: Int
    let status: OrderStatus
    let orderNumber: String
    let reciept: String
    let sum: Float
    let pickupTime: String
    let pickupDate: String
    let deliveryTime: String
    let deliveryDate: String
    let paymentType: PaymentType?
    let estimate: Int
    let hasDelivery: Bool
    let pickupPointDate: String
    let pickupPointAdress: String
}
