//
//  TrustArrangementViewController.swift
//  contrast
//
//  Created by Kotovchikhin Vladimir on 06.07.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import PanModal

protocol TrustArrangementDisplayLogic: AnyObject {
    func display(viewModel: TrustArrangement.Model.ViewModel.ViewModelType)
}

final class TrustArrangementViewController: UIViewController {
    
    // MARK: - IBOutlets
    private let indicatorView: UIView = {
        let view = UIView()
        view.backgroundColor = .textLight
        view.layer.cornerRadius = 2.5
        return view
    }()
    
    private let imageView: UIImageView = {
        let image = UIImageView()
        return image
    }()
    
    private let titleLabel: UILabel = {
        let label = UILabel()
        label.numberOfLines = 0
        label.font = GeneralFonts.generalRegular17
        label.textAlignment = .center
        label.textColor = .textDark
        return label
    }()
    
    private let descriptionLabel: UILabel = {
        let label = UILabel()
        label.numberOfLines = 0
        label.font = GeneralFonts.generalRegular11
        label.textAlignment = .center
        label.textColor = .textLight
        return label
    }()
    
    private let closeButton: MainButton = {
        let button = MainButton()
        button.setTitle(R.string.localizable.close(), for: .normal)
        return button
    }()
    
    // MARK: - External vars
    var interactor: TrustArrangementBusinessLogic?
    var router: (NSObjectProtocol & TrustArrangementRoutingLogic & TrustArrangementDataPassing)?
    var panScrollable: UIScrollView?
    
    // MARK: - Internal vars
    
    
    // MARK: - Object lifecycle
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        TrustArrangementConfigurator.shared.configure(self)
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        TrustArrangementConfigurator.shared.configure(self)
    }
    
    // MARK: - View lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
        setupView()
    }
}

// MARK: - Display logic
extension TrustArrangementViewController: TrustArrangementDisplayLogic {
    
    func display(viewModel: TrustArrangement.Model.ViewModel.ViewModelType) {
        switch viewModel {
            //case .some
        }
    }
}

// MARK: - Private methods
private extension TrustArrangementViewController {
    private func setupView() {
        view.backgroundColor = .mainBackgroundColor
        
        view.addSubview(indicatorView)
        view.addSubview(imageView)
        view.addSubview(titleLabel)
        view.addSubview(descriptionLabel)
        view.addSubview(closeButton)
        
        fetchData()
        
        closeButton.addTarget(self, action: #selector(pressCloseButton), for: .touchUpInside)
        setupConstraint()
    }
    
    private func fetchData() {
        imageView.image = router?.dataStore?.image
        titleLabel.text = router?.dataStore?.title
        descriptionLabel.text = router?.dataStore?.desc
    }
    
    private func setupConstraint() {
        
        indicatorView.snp.makeConstraints {
            $0.top.equalToSuperview().inset(8)
            $0.centerX.equalToSuperview()
            $0.width.equalTo(60)
            $0.height.equalTo(5)
        }
        
        imageView.snp.makeConstraints {
            $0.top.equalTo(indicatorView.snp.bottom).offset(28)
            $0.centerX.equalToSuperview()
            $0.width.height.equalTo(96)
        }
        
        titleLabel.snp.makeConstraints {
            $0.top.equalTo(imageView.snp.bottom).offset(8)
            $0.leading.trailing.equalToSuperview().inset(16)
        }
        
        descriptionLabel.snp.makeConstraints {
            $0.top.equalTo(titleLabel.snp.bottom).offset(5)
            $0.leading.trailing.equalToSuperview().inset(16)
        }
        
        closeButton.snp.makeConstraints {
            $0.top.equalTo(descriptionLabel.snp.bottom).offset(55)
            $0.leading.trailing.equalToSuperview().inset(16)
            $0.bottom.equalToSuperview().inset(38)
            $0.height.equalTo(46)
        }
    }
    
    @objc private func pressCloseButton() {
        router?.dismissScreen()
    }
}

// MARK: - Public methods
extension TrustArrangementViewController: PanModalPresentable {
    
    var longFormHeight: PanModalHeight {
        return .intrinsicHeight
    }
    
    override var preferredStatusBarStyle: UIStatusBarStyle {
        return .lightContent
    }
    
    var showDragIndicator: Bool {
        return false
    }
}


