//
//  TrustArrangementRouter.swift
//  contrast
//
//  Created by Kotovchikhin Vladimir on 06.07.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TrustArrangementRoutingLogic {
    func dismissScreen()
}

protocol TrustArrangementDataPassing {
    var dataStore: TrustArrangementDataStore? { get }
}

final class TrustArrangementRouter: NSObject {
    
    // MARK: - External vars
    weak var viewController: TrustArrangementViewController?
    var dataStore: TrustArrangementDataStore?
    
    // MARK: - Internal vars
    
}

// MARK: - Routing logic
extension TrustArrangementRouter: TrustArrangementRoutingLogic {
    func dismissScreen() {
        viewController?.dismiss(animated: true, completion: nil)
    }
}

// MARK: - Data passing
extension TrustArrangementRouter: TrustArrangementDataPassing {
    
}
