//
//  NotificationsRouter.swift
//  contrast
//
//  Created by Александра Орлова on 03.07.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NotificationsRoutingLogic {
    
}

protocol NotificationsDataPassing {
    var dataStore: NotificationsDataStore? { get }
}

final class NotificationsRouter: NSObject {
    
    // MARK: - External vars
    weak var viewController: NotificationsViewController?
    var dataStore: NotificationsDataStore?
    
    // MARK: - Internal vars
    
}

// MARK: - Routing logic
extension NotificationsRouter: NotificationsRoutingLogic {
    
}

// MARK: - Data passing
extension NotificationsRouter: NotificationsDataPassing {
    
}
