//
//  NotificationsInteractor.swift
//  contrast
//
//  Created by Александра Орлова on 03.07.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NotificationsBusinessLogic {
    func make(request: Notifications.Model.Request.RequestType)
}

protocol NotificationsDataStore: AnyObject {
    
}

final class NotificationsInteractor {
    
    // MARK: - External vars
    var presenter: NotificationsPresentationLogic?
    var worker: NotificationsWorker?
    
    // MARK: - Internal vars
    private let service: Services
    
    init(service: NetworkServiceable) {
        self.service = Services(service: service)
    }
}

// MARK: - Business logic
extension NotificationsInteractor: NotificationsBusinessLogic {
    
    func make(request: Notifications.Model.Request.RequestType) {
        switch request {
            //case .some:
        }
    }
}

// MARK: - Data store
extension NotificationsInteractor: NotificationsDataStore  {
   
}

// MARK: - Private methods
private extension NotificationsInteractor {
    
}
