//
//  NotificationsConfigurator.swift
//  contrast
//
//  Created by Александра Орлова on 03.07.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

final class NotificationsConfigurator {
    
    static let shared = NotificationsConfigurator()
    private init() {}
    
    func configure(_ viewController: NotificationsViewController) {
        let service = NetworkService()
        let interactor = NotificationsInteractor(service: service)
        let presenter = NotificationsPresenter()
        let router = NotificationsRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
}
