//
//  NotificationsModels.swift
//  contrast
//
//  Created by Александра Орлова on 03.07.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Notifications {
    
    enum Model {
        struct Request {
            enum RequestType {
                
            }
        }
        struct Response {
            enum ResponseType {
                
            }
        }
        struct ViewModel {
            enum ViewModelType {
                
            }
        }
    }
}

struct NotificationsModel {
    let date: String
    let notification: [NotificationItem]
}

struct NotificationItem {
    let message: String
    let time: String
    let hasQuestion: Bool
}
