//
//  NotificationsPresenter.swift
//  contrast
//
//  Created by Александра Орлова on 03.07.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NotificationsPresentationLogic {
    func presentData(response: Notifications.Model.Response.ResponseType)
}

final class NotificationsPresenter {
    
    // MARK: - External vars
    weak var viewController: NotificationsDisplayLogic?
    
}

// MARK: - Presentation logic
extension NotificationsPresenter: NotificationsPresentationLogic {
    
    func presentData(response: Notifications.Model.Response.ResponseType) {
        switch response {
            //case .some:
        }
    }
}

//  MARK: - Private  methods
private extension NotificationsPresenter {
    
}
