//
//  EstimateOrderConfigurator.swift
//  contrast
//
//  Created by Александра Орлова on 04.07.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

final class EstimateOrderConfigurator {
    
    static let shared = EstimateOrderConfigurator()
    private init() {}
    
    func configure(_ viewController: EstimateOrderViewController) {
        let service = NetworkService()
        let interactor = EstimateOrderInteractor(service: service)
        let presenter = EstimateOrderPresenter()
        let router = EstimateOrderRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
}
