//
//  EstimateOrderInteractor.swift
//  contrast
//
//  Created by Александра Орлова on 04.07.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EstimateOrderBusinessLogic {
    func make(request: EstimateOrder.Model.Request.RequestType)
}

protocol EstimateOrderDataStore: AnyObject {
    
}

final class EstimateOrderInteractor {
    
    // MARK: - External vars
    var presenter: EstimateOrderPresentationLogic?
    var worker: EstimateOrderWorker?
    
    // MARK: - Internal vars
    private let service: Services
    
    init(service: NetworkServiceable) {
        self.service = Services(service: service)
    }
}

// MARK: - Business logic
extension EstimateOrderInteractor: EstimateOrderBusinessLogic {
    
    func make(request: EstimateOrder.Model.Request.RequestType) {
        switch request {
            //case .some:
        }
    }
}

// MARK: - Data store
extension EstimateOrderInteractor: EstimateOrderDataStore  {
   
}

// MARK: - Private methods
private extension EstimateOrderInteractor {
    
}
