//
//  EstimateOrderRouter.swift
//  contrast
//
//  Created by Александра Орлова on 04.07.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EstimateOrderRoutingLogic {
    func routeToMain()
}

protocol EstimateOrderDataPassing {
    var dataStore: EstimateOrderDataStore? { get }
}

final class EstimateOrderRouter: NSObject {
    
    // MARK: - External vars
    weak var viewController: EstimateOrderViewController?
    var dataStore: EstimateOrderDataStore?
    
    // MARK: - Internal vars
    
}

// MARK: - Routing logic
extension EstimateOrderRouter: EstimateOrderRoutingLogic {
    func routeToMain() {
        viewController?.dismiss(animated: true)
    }
}

// MARK: - Data passing
extension EstimateOrderRouter: EstimateOrderDataPassing {
    
}
