//
//  PaymentMethodConfigurator.swift
//  contrast
//
//  Created by Александра Орлова on 05.07.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

final class PaymentMethodConfigurator {
    
    static let shared = PaymentMethodConfigurator()
    private init() {}
    
    func configure(_ viewController: PaymentMethodViewController) {
        let service = NetworkService()
        let interactor = PaymentMethodInteractor(service: service)
        let presenter = PaymentMethodPresenter()
        let router = PaymentMethodRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
}
