//
//  PaymentMethodInteractor.swift
//  contrast
//
//  Created by Александра Орлова on 05.07.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PaymentMethodBusinessLogic {
    func make(request: PaymentMethod.Model.Request.RequestType)
}

protocol PaymentMethodDataStore: AnyObject {
    
}

final class PaymentMethodInteractor {
    
    // MARK: - External vars
    var presenter: PaymentMethodPresentationLogic?
    var worker: PaymentMethodWorker?
    
    // MARK: - Internal vars
    private let service: Services
    
    init(service: NetworkServiceable) {
        self.service = Services(service: service)
    }
}

// MARK: - Business logic
extension PaymentMethodInteractor: PaymentMethodBusinessLogic {
    
    func make(request: PaymentMethod.Model.Request.RequestType) {
        switch request {
            //case .some:
        }
    }
}

// MARK: - Data store
extension PaymentMethodInteractor: PaymentMethodDataStore  {
   
}

// MARK: - Private methods
private extension PaymentMethodInteractor {
    
}
