//
//  PaymentMethodPresenter.swift
//  contrast
//
//  Created by Александра Орлова on 05.07.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PaymentMethodPresentationLogic {
    func presentData(response: PaymentMethod.Model.Response.ResponseType)
}

final class PaymentMethodPresenter {
    
    // MARK: - External vars
    weak var viewController: PaymentMethodDisplayLogic?
    
}

// MARK: - Presentation logic
extension PaymentMethodPresenter: PaymentMethodPresentationLogic {
    
    func presentData(response: PaymentMethod.Model.Response.ResponseType) {
        switch response {
            //case .some:
        }
    }
}

//  MARK: - Private  methods
private extension PaymentMethodPresenter {
    
}
