//
//  PaymentMethodRouter.swift
//  contrast
//
//  Created by Александра Орлова on 05.07.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PaymentMethodRoutingLogic {
    func routeToMain()
    func routeToLinked(cards: [CardModel], orderModel: NewOrderModel)
    func routeToPaymentConfirmation(model: NewOrderModel)
    func routeToLinkNewCard(model: NewOrderModel)
}

protocol PaymentMethodDataPassing {
    var dataStore: PaymentMethodDataStore? { get }
}

final class PaymentMethodRouter: NSObject {
    
    // MARK: - External vars
    weak var viewController: PaymentMethodViewController?
    var dataStore: PaymentMethodDataStore?
    
    // MARK: - Internal vars
    
}

// MARK: - Routing logic
extension PaymentMethodRouter: PaymentMethodRoutingLogic {
    func routeToMain() {
        viewController?.dismiss(animated: true)
    }
    
    func routeToLinked(cards: [CardModel], orderModel: NewOrderModel) {
        let vc = LinkedCardsViewController()
        vc.router?.dataStore?.cards = cards
        vc.router?.dataStore?.orderModel = orderModel
        let navController = UINavigationController(rootViewController: vc)
        navController.modalPresentationStyle = .fullScreen
        viewController?.present(navController, animated: true)
    }
    
    func routeToPaymentConfirmation(model: NewOrderModel) {
        let vc = PaymentConfirmationViewController()
        vc.router?.dataStore?.order = model
        let navController = UINavigationController(rootViewController: vc)
        navController.modalPresentationStyle = .fullScreen
        viewController?.present(navController, animated: true)
    }
    
    func routeToLinkNewCard(model: NewOrderModel) {
        let vc = LinkNewCardViewController()
        vc.router?.dataStore?.order = model
        let navController = UINavigationController(rootViewController: vc)
        navController.modalPresentationStyle = .fullScreen
        viewController?.present(navController, animated: true)
    }
}

// MARK: - Data passing
extension PaymentMethodRouter: PaymentMethodDataPassing {
    
}
