//
//  addPhotosInOrderingInteractor.swift
//  contrast
//
//  Created by Vladimir Kotovchikhin on 18.07.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol addPhotosInOrderingBusinessLogic {
    func make(request: addPhotosInOrdering.Model.Request.RequestType)
}

protocol addPhotosInOrderingDataStore: AnyObject {
    
}

final class addPhotosInOrderingInteractor {
    
    // MARK: - External vars
    var presenter: addPhotosInOrderingPresentationLogic?
    var worker: addPhotosInOrderingWorker?
    
    // MARK: - Internal vars
    private let service: Services
    
    init(service: NetworkServiceable) {
        self.service = Services(service: service)
    }
}

// MARK: - Business logic
extension addPhotosInOrderingInteractor: addPhotosInOrderingBusinessLogic {
    
    func make(request: addPhotosInOrdering.Model.Request.RequestType) {
        switch request {
            //case .some:
        }
    }
}

// MARK: - Data store
extension addPhotosInOrderingInteractor: addPhotosInOrderingDataStore  {
   
}

// MARK: - Private methods
private extension addPhotosInOrderingInteractor {
    
}
