//
//  OrderСancellationRouter.swift
//  contrast
//
//  Created by Владимир on 05.07.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol OrderСancellationRoutingLogic {
    func dismissScreen()
}

protocol OrderСancellationDataPassing {
    var dataStore: OrderСancellationDataStore? { get }
}

final class OrderСancellationRouter: NSObject {
    
    // MARK: - External vars
    weak var viewController: OrderСancellationViewController?
    var dataStore: OrderСancellationDataStore?
    
    // MARK: - Internal vars
    
}

// MARK: - Routing logic
extension OrderСancellationRouter: OrderСancellationRoutingLogic {
    func dismissScreen() {
        viewController?.dismiss(animated: true, completion: nil)
    }
}

// MARK: - Data passing
extension OrderСancellationRouter: OrderСancellationDataPassing {
    
}
