//
//  LinkedCardsRouter.swift
//  contrast
//
//  Created by Александра Орлова on 06.07.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LinkedCardsRoutingLogic {
    func routeToPayConfirmation(withOrder: NewOrderModel)
    func routeToLinkNewCard(withOrder: NewOrderModel)
}

protocol LinkedCardsDataPassing {
    var dataStore: LinkedCardsDataStore? { get }
}

final class LinkedCardsRouter: NSObject {
    
    // MARK: - External vars
    weak var viewController: LinkedCardsViewController?
    var dataStore: LinkedCardsDataStore?
    
    // MARK: - Internal vars
    
}

// MARK: - Routing logic
extension LinkedCardsRouter: LinkedCardsRoutingLogic {
    func routeToLinkNewCard(withOrder value: NewOrderModel) {
        let vc = LinkNewCardViewController()
        vc.router?.dataStore?.order = value
        viewController?.navigationController?.pushViewController(vc, animated: true)
    }
    
    func routeToPayConfirmation(withOrder value: NewOrderModel) {
        let vc = PaymentConfirmationViewController()
        vc.router?.dataStore?.order = value
        viewController?.navigationController?.pushViewController(vc, animated: true)
    }
}

// MARK: - Data passing
extension LinkedCardsRouter: LinkedCardsDataPassing {
    
}
