//
//  LinkedCardsPresenter.swift
//  contrast
//
//  Created by Александра Орлова on 06.07.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LinkedCardsPresentationLogic {
    func presentData(response: LinkedCards.Model.Response.ResponseType)
}

final class LinkedCardsPresenter {
    
    // MARK: - External vars
    weak var viewController: LinkedCardsDisplayLogic?
    
}

// MARK: - Presentation logic
extension LinkedCardsPresenter: LinkedCardsPresentationLogic {
    
    func presentData(response: LinkedCards.Model.Response.ResponseType) {
        switch response {
            //case .some:
        }
    }
}

//  MARK: - Private  methods
private extension LinkedCardsPresenter {
    
}
