//
//  LoginModels.swift
//  contrast
//
//  Created by Roman Kiruxin on 03.07.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Login {
    
    enum Model {
        struct Request {
            enum RequestType {
                case sendSms(_ phone: String, type: Int)
            }
        }
        struct Response {
            enum ResponseType {
                case success(_ response: UserAuthResponse)
            }
        }
        struct ViewModel {
            enum ViewModelType {
                case success(_ viewModel: UserAuthResponse)
            }
        }
    }
}

