//
//  LoginConfigurator.swift
//  contrast
//
//  Created by Roman Kiruxin on 03.07.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

final class LoginConfigurator {
    
    static let shared = LoginConfigurator()
    private init() {}
    
    func configure(_ viewController: LoginViewController) {
        let service = NetworkService()
        let interactor = LoginInteractor(service: service)
        let presenter = LoginPresenter()
        let router = LoginRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
}
