//
//  LoginRouter.swift
//  contrast
//
//  Created by Roman Kiruxin on 03.07.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginRoutingLogic {
    func routeToVerify(withTimer timer: Int?, and verifyType: Int)
}

protocol LoginDataPassing {
    var dataStore: LoginDataStore? { get }
}

final class LoginRouter: NSObject {
    
    // MARK: - External vars
    weak var viewController: LoginViewController?
    var dataStore: LoginDataStore?
    
    // MARK: - Internal vars
    
}

// MARK: - Routing logic
extension LoginRouter: LoginRoutingLogic {
    func routeToVerify(withTimer timer: Int?, and verifyType: Int) {
        let vc = SmsConfirmViewController()
        vc.router?.dataStore?.timer = timer
        vc.router?.dataStore?.verifyType = verifyType
        viewController?.navigationController?.pushViewController(vc, animated: true)
    }
}

// MARK: - Data passing
extension LoginRouter: LoginDataPassing {
    
}
