//
//  LoginPresenter.swift
//  contrast
//
//  Created by Roman Kiruxin on 03.07.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic {
    func presentData(response: Login.Model.Response.ResponseType)
}

final class LoginPresenter {
    
    // MARK: - External vars
    weak var viewController: LoginDisplayLogic?
    
}

// MARK: - Presentation logic
extension LoginPresenter: LoginPresentationLogic {
    
    func presentData(response: Login.Model.Response.ResponseType) {
        switch response {
        case .success(let response):
            viewController?.display(viewModel: .success(response))
        }
    }
}

//  MARK: - Private  methods
private extension LoginPresenter {
    
}
