//
//  PaymentSuccessPresenter.swift
//  contrast
//
//  Created by Александра Орлова on 06.07.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PaymentSuccessPresentationLogic {
    func presentData(response: PaymentSuccess.Model.Response.ResponseType)
}

final class PaymentSuccessPresenter {
    
    // MARK: - External vars
    weak var viewController: PaymentSuccessDisplayLogic?
    
}

// MARK: - Presentation logic
extension PaymentSuccessPresenter: PaymentSuccessPresentationLogic {
    
    func presentData(response: PaymentSuccess.Model.Response.ResponseType) {
        switch response {
            //case .some:
        }
    }
}

//  MARK: - Private  methods
private extension PaymentSuccessPresenter {
    
}
