//
//  PaymentSuccessConfigurator.swift
//  contrast
//
//  Created by Александра Орлова on 06.07.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

final class PaymentSuccessConfigurator {
    
    static let shared = PaymentSuccessConfigurator()
    private init() {}
    
    func configure(_ viewController: PaymentSuccessViewController) {
        let service = NetworkService()
        let interactor = PaymentSuccessInteractor(service: service)
        let presenter = PaymentSuccessPresenter()
        let router = PaymentSuccessRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
}
