//
//  PaymentSuccessRouter.swift
//  contrast
//
//  Created by Александра Орлова on 06.07.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PaymentSuccessRoutingLogic {
    func routeToMain()
}

protocol PaymentSuccessDataPassing {
    var dataStore: PaymentSuccessDataStore? { get }
}

final class PaymentSuccessRouter: NSObject {
    
    // MARK: - External vars
    weak var viewController: PaymentSuccessViewController?
    var dataStore: PaymentSuccessDataStore?
    
    // MARK: - Internal vars
    
}

// MARK: - Routing logic
extension PaymentSuccessRouter: PaymentSuccessRoutingLogic {
    func routeToMain() {
        let vc = TabbarViewController()
        viewController?.navigationController?.pushViewController(vc, animated: true)
    }
}

// MARK: - Data passing
extension PaymentSuccessRouter: PaymentSuccessDataPassing {
    
}
