//
//  PaymentSuccessInteractor.swift
//  contrast
//
//  Created by Александра Орлова on 06.07.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PaymentSuccessBusinessLogic {
    func make(request: PaymentSuccess.Model.Request.RequestType)
}

protocol PaymentSuccessDataStore: AnyObject {
    
}

final class PaymentSuccessInteractor {
    
    // MARK: - External vars
    var presenter: PaymentSuccessPresentationLogic?
    var worker: PaymentSuccessWorker?
    
    // MARK: - Internal vars
    private let service: Services
    
    init(service: NetworkServiceable) {
        self.service = Services(service: service)
    }
}

// MARK: - Business logic
extension PaymentSuccessInteractor: PaymentSuccessBusinessLogic {
    
    func make(request: PaymentSuccess.Model.Request.RequestType) {
        switch request {
            //case .some:
        }
    }
}

// MARK: - Data store
extension PaymentSuccessInteractor: PaymentSuccessDataStore  {
   
}

// MARK: - Private methods
private extension PaymentSuccessInteractor {
    
}
