//
//  CatalogRouter.swift
//  contrast
//
//  Created by Roman Kiruxin on 29.06.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CatalogRoutingLogic {
    func routeToMap()
}

protocol CatalogDataPassing {
    var dataStore: CatalogDataStore? { get }
}

final class CatalogRouter: NSObject {
    
    // MARK: - External vars
    weak var viewController: CatalogViewController?
    var dataStore: CatalogDataStore?
    
    // MARK: - Internal vars
    
}

// MARK: - Routing logic
extension CatalogRouter: CatalogRoutingLogic {
    func routeToMap() {
        let vc = MapViewController()
        vc.modalPresentationStyle = .fullScreen
        viewController?.present(vc, animated: true)
    }
}

// MARK: - Data passing
extension CatalogRouter: CatalogDataPassing {
    
}
