//
//  TabbarPresenter.swift
//  contrast
//
//  Created by Roman Kiruxin on 29.06.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TabbarPresentationLogic {
    func presentData(response: Tabbar.Model.Response.ResponseType)
}

final class TabbarPresenter {
    
    // MARK: - External vars
    weak var viewController: TabbarDisplayLogic?
    
}

// MARK: - Presentation logic
extension TabbarPresenter: TabbarPresentationLogic {
    
    func presentData(response: Tabbar.Model.Response.ResponseType) {
        switch response {
            //case .some:
        }
    }
}

//  MARK: - Private  methods
private extension TabbarPresenter {
    
}
