//
//  PaymentConfirmationConfigurator.swift
//  contrast
//
//  Created by Александра Орлова on 06.07.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

final class PaymentConfirmationConfigurator {
    
    static let shared = PaymentConfirmationConfigurator()
    private init() {}
    
    func configure(_ viewController: PaymentConfirmationViewController) {
        let service = NetworkService()
        let interactor = PaymentConfirmationInteractor(service: service)
        let presenter = PaymentConfirmationPresenter()
        let router = PaymentConfirmationRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
}
