//
//  PaymentConfirmationRouter.swift
//  contrast
//
//  Created by Александра Орлова on 06.07.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PaymentConfirmationRoutingLogic {
    func routeToPay()
    func routeBack()
}

protocol PaymentConfirmationDataPassing {
    var dataStore: PaymentConfirmationDataStore? { get }
}

final class PaymentConfirmationRouter: NSObject {
    
    // MARK: - External vars
    weak var viewController: PaymentConfirmationViewController?
    var dataStore: PaymentConfirmationDataStore?
    
    // MARK: - Internal vars
    
}

// MARK: - Routing logic
extension PaymentConfirmationRouter: PaymentConfirmationRoutingLogic {
    func routeToPay() {
        let vc = PaymentSuccessViewController()
        viewController?.navigationController?.pushViewController(vc, animated: true)
    }
    
    func routeBack() {
        viewController?.navigationController?.popViewController(animated: true)
        
        if let presentingViewController = viewController?.presentingViewController {
            presentingViewController.dismiss(animated: true, completion: nil)
        }
    }
}

// MARK: - Data passing
extension PaymentConfirmationRouter: PaymentConfirmationDataPassing {
    
}
