//
//  SearchAddressesModels.swift
//  contrast
//
//  Created by Roman Kiruxin on 18.07.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum SearchAddresses {
    
    enum Model {
        struct Request {
            enum RequestType {
                case fetchAdresses(_ address: String)
            }
        }
        struct Response {
            enum ResponseType {
                case addresses(_ response: [AddressData])
            }
        }
        struct ViewModel {
            enum ViewModelType {
                case presentAddresses(_ viewModel: [AddressDataModel])
            }
        }
    }
}
