//
//  DocumentsRouter.swift
//  contrast
//
//  Created by Roman Kiruxin on 05.07.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DocumentsRoutingLogic {
    
}

protocol DocumentsDataPassing {
    var dataStore: DocumentsDataStore? { get }
}

final class DocumentsRouter: NSObject {
    
    // MARK: - External vars
    weak var viewController: DocumentsViewController?
    var dataStore: DocumentsDataStore?
    
    // MARK: - Internal vars
    
}

// MARK: - Routing logic
extension DocumentsRouter: DocumentsRoutingLogic {
    
}

// MARK: - Data passing
extension DocumentsRouter: DocumentsDataPassing {
    
}
