//
//  DocumentsPresenter.swift
//  contrast
//
//  Created by Roman Kiruxin on 05.07.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DocumentsPresentationLogic {
    func presentData(response: Documents.Model.Response.ResponseType)
}

final class DocumentsPresenter {
    
    // MARK: - External vars
    weak var viewController: DocumentsDisplayLogic?
    
}

// MARK: - Presentation logic
extension DocumentsPresenter: DocumentsPresentationLogic {
    
    func presentData(response: Documents.Model.Response.ResponseType) {
        switch response {
        case .nameScreen(let nameScreen):
            viewController?.display(viewModel: .presentNameScreen(nameScreen))
        case .urlReceipt(let url):
            viewController?.display(viewModel: .presentUrlReceipt(url))
        }
    }
}

//  MARK: - Private  methods
private extension DocumentsPresenter {
    
}
