//
//  DocumentsConfigurator.swift
//  contrast
//
//  Created by Roman Kiruxin on 05.07.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

final class DocumentsConfigurator {
    
    static let shared = DocumentsConfigurator()
    private init() {}
    
    func configure(_ viewController: DocumentsViewController) {
        let service = NetworkService()
        let interactor = DocumentsInteractor(service: service)
        let presenter = DocumentsPresenter()
        let router = DocumentsRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
}
