//
//  TimeIntervalsOrderingPresenter.swift
//  contrast
//
//  Created by Roman Kiruxin on 20.07.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TimeIntervalsOrderingPresentationLogic {
    func presentData(response: TimeIntervalsOrdering.Model.Response.ResponseType)
}

final class TimeIntervalsOrderingPresenter {
    
    // MARK: - External vars
    weak var viewController: TimeIntervalsOrderingDisplayLogic?
    
}

// MARK: - Presentation logic
extension TimeIntervalsOrderingPresenter: TimeIntervalsOrderingPresentationLogic {
    
    func presentData(response: TimeIntervalsOrdering.Model.Response.ResponseType) {
        switch response {
            //case .some:
        }
    }
}

//  MARK: - Private  methods
private extension TimeIntervalsOrderingPresenter {
    
}
