//
//  TimeIntervalsOrderingConfigurator.swift
//  contrast
//
//  Created by Roman Kiruxin on 20.07.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

final class TimeIntervalsOrderingConfigurator {
    
    static let shared = TimeIntervalsOrderingConfigurator()
    private init() {}
    
    func configure(_ viewController: TimeIntervalsOrderingViewController) {
        let service = NetworkService()
        let interactor = TimeIntervalsOrderingInteractor(service: service)
        let presenter = TimeIntervalsOrderingPresenter()
        let router = TimeIntervalsOrderingRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
}
