//
//  SuccessOrderPresenter.swift
//  contrast
//
//  Created by Roman Kiruxin on 21.07.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SuccessOrderPresentationLogic {
    func presentData(response: SuccessOrder.Model.Response.ResponseType)
}

final class SuccessOrderPresenter {
    
    // MARK: - External vars
    weak var viewController: SuccessOrderDisplayLogic?
    
}

// MARK: - Presentation logic
extension SuccessOrderPresenter: SuccessOrderPresentationLogic {
    
    func presentData(response: SuccessOrder.Model.Response.ResponseType) {
        switch response {
            //case .some:
        }
    }
}

//  MARK: - Private  methods
private extension SuccessOrderPresenter {
    
}
