//
//  SuccessOrderRouter.swift
//  contrast
//
//  Created by Roman Kiruxin on 21.07.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SuccessOrderRoutingLogic {
    func routeToMain()
}

protocol SuccessOrderDataPassing {
    var dataStore: SuccessOrderDataStore? { get }
}

final class SuccessOrderRouter: NSObject {
    
    // MARK: - External vars
    weak var viewController: SuccessOrderViewController?
    var dataStore: SuccessOrderDataStore?
    
    // MARK: - Internal vars
    
}

// MARK: - Routing logic
extension SuccessOrderRouter: SuccessOrderRoutingLogic {
    func routeToMain() {
        let vc = TabbarViewController()
        let navigation = UINavigationController(rootViewController: vc)
        navigation.isNavigationBarHidden = true
        let sceneDelegate = UIApplication.shared.connectedScenes.first?.delegate as? SceneDelegate
        sceneDelegate?.window?.rootViewController = navigation
    }
}

// MARK: - Data passing
extension SuccessOrderRouter: SuccessOrderDataPassing {
    
}
