//
//  SuccessOrderInteractor.swift
//  contrast
//
//  Created by Roman Kiruxin on 21.07.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SuccessOrderBusinessLogic {
    func make(request: SuccessOrder.Model.Request.RequestType)
}

protocol SuccessOrderDataStore: AnyObject {
    var selectedDate: String? { get set }
    var selectedTime: String? { get set }
}

final class SuccessOrderInteractor {
    
    // MARK: - External vars
    var presenter: SuccessOrderPresentationLogic?
    var worker: SuccessOrderWorker?
    
    // MARK: - Internal vars
    private let service: Services
    var selectedDate: String?
    var selectedTime: String? 
    
    init(service: NetworkServiceable) {
        self.service = Services(service: service)
    }
}

// MARK: - Business logic
extension SuccessOrderInteractor: SuccessOrderBusinessLogic {
    
    func make(request: SuccessOrder.Model.Request.RequestType) {
        switch request {
            //case .some:
        }
    }
}

// MARK: - Data store
extension SuccessOrderInteractor: SuccessOrderDataStore  {
   
}

// MARK: - Private methods
private extension SuccessOrderInteractor {
    
}
